version: '3.4'

services:
  healthexplore.job.api:
    image: ${DOCKER_REGISTRY-}healthexplorejob
    build:
      context: .
      dockerfile: healthexplore.job.api/Dockerfile

  healthexplore.filters.api:
    image: ${DOCKER_REGISTRY-}healthexplorefilters
    build:
      context: .
      dockerfile: healthexplore.filters.api/Dockerfile